### ISSUE TITLE
Is download correct?

### ISSUE THREAD

**Issue by androhi** [tomoima525/debot#1]
I'm tring this library, but fail the gradle sync.
I was successful try the following code.

```gradle
dependencies {
  debugCompile 'com.tomoima.debot:debot:1.0.1'
  releaseCompile 'com.tomoima.debot:debot-no-op:1.0.1'
  ...
```

**Comment by androhi** [comment]
I refferenced this.
http://tools.android.com/tech-docs/new-build-system/user-guide#TOC-Dependencies-Android-Libraries-and-Multi-project-setup

**Comment by tomoima525** [comment]
Hi @androhi , thank you for the comment. You are totally right. I miss copied the wrong file name. Will create a branch and fix this.

**Comment by tomoima525** [comment]
Will close this issue since fix has been applied.

**Comment by androhi** [comment]
Thank you to fix!
