### ISSUE TITLE
DebotStrategy is not Serializable

### ISSUE THREAD

**Issue by hkurokawa** [tomoima525/debot#20]
As you put your ArrayList of `DebotStrategy` to the Fragment arguments with `putSerializable`, you have to make sure `DebotStrategy` implements Serializable.
https://github.com/tomoima525/debot/blob/02921b0209cb0ee3335f9c371f2594e6fa4f982d/debot/src/main/java/com/tomoima/debot/DebotDialog.java#L29

This causes an error when you try to save `DebotFragment` just like https://github.com/DroidKaigi/conference-app-2017/issues/254

Thanks.

**Comment by tomoima525** [comment]
Thank you, will take a look and fix this issue

**Comment by hkurokawa** [comment]
@tomoima525 Thank you for your prompt action. Do you have any timeline on the release? I would like to update your library in the DroidKaigi app when you published a new release including the fix.

Thanks.

**Comment by tomoima525** [comment]
@hkurokawa Hi, I just made another PR to fix to this issue. I will release the new version as soon as this fix is passed

**Comment by tomoima525** [comment]
Made a PR for the fix https://github.com/DroidKaigi/conference-app-2017/pull/357
